/* ISTQB Glossary — Foundation level (239 terms)
   en = English term, ru = Russian term
   de = official English definition (verbatim, glossary.istqb.org)
   dr = Russian translation of the official definition
   t  = topic code (see TOPICS in index.html)
   Source: https://glossary.istqb.org/en_US  (definitions EN are authoritative;
   RU are faithful translations — ISTQB international API has no RU definitions). */
window.TERMS = [
{en:"acceptance criteria",ru:"критерии приёмки",t:"process",
 de:"The criteria that a work product must satisfy to be accepted by the stakeholders.",
 dr:"Критерии, которым должен удовлетворять рабочий продукт, чтобы быть принятым заинтересованными сторонами."},
{en:"acceptance test-driven development",ru:"разработка через приёмочное тестирование (ATDD)",t:"agile",
 de:"A collaboration-based test-first approach that defines acceptance tests in the stakeholders' domain language.",
 dr:"Совместный подход «тестирование вперёд», при котором приёмочные тесты задаются на предметном языке заинтересованных сторон."},
{en:"acceptance testing",ru:"приёмочное тестирование",t:"levels",
 de:"A test level that focuses on determining whether to accept the system.",
 dr:"Уровень тестирования, сфокусированный на принятии решения, принимать ли систему."},
{en:"actual result",ru:"фактический результат",t:"process",
 de:"The behavior produced/observed when a component or system is tested.",
 dr:"Поведение, полученное или наблюдаемое при тестировании компонента или системы."},
{en:"Agile Manifesto",ru:"Agile-манифест",t:"agile",
 de:"A statement on the values that underpin Agile software development. The values are: individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, responding to change over following a plan.",
 dr:"Заявление о ценностях, лежащих в основе гибкой (Agile) разработки ПО. Ценности: люди и взаимодействие важнее процессов и инструментов; работающее ПО важнее исчерпывающей документации; сотрудничество с заказчиком важнее согласования условий контракта; готовность к изменениям важнее следования плану."},
{en:"Agile software development",ru:"гибкая (Agile) разработка ПО",t:"agile",
 de:"A group of software development lifecycle models based on iterative incremental development, where requirements and solutions evolve through collaboration between self-organizing cross-functional teams.",
 dr:"Группа моделей жизненного цикла разработки ПО, основанных на итеративно-инкрементальной разработке, где требования и решения развиваются через сотрудничество самоорганизующихся кросс-функциональных команд."},
{en:"alpha testing",ru:"альфа-тестирование",t:"levels",
 de:"A type of acceptance testing performed in the developer's test environment by roles outside the development organization.",
 dr:"Вид приёмочного тестирования, выполняемый в тестовой среде разработчика лицами вне организации-разработчика."},
{en:"anomaly",ru:"аномалия",t:"defect",
 de:"A condition that deviates from expectation.",
 dr:"Состояние, отклоняющееся от ожидаемого."},
{en:"API testing",ru:"тестирование API",t:"types",
 de:"A test approach performed by submitting requests to a test object using its application programming interface.",
 dr:"Подход к тестированию, выполняемый путём отправки запросов к объекту тестирования через его программный интерфейс (API)."},
{en:"appropriateness recognizability",ru:"распознаваемость пригодности",t:"quality",
 de:"The degree to which users can recognize whether a component or system is appropriate for their needs.",
 dr:"Степень, в которой пользователи могут распознать, подходит ли компонент или система их потребностям."},
{en:"audit",ru:"аудит",t:"static",
 de:"An independent examination performed by a third party on a work product or process to assess whether it complies with specified criteria.",
 dr:"Независимая проверка рабочего продукта или процесса третьей стороной для оценки его соответствия заданным критериям."},
{en:"availability",ru:"доступность",t:"quality",
 de:"The degree to which a component or system is operational and accessible when required for use.",
 dr:"Степень, в которой компонент или система работоспособны и доступны, когда требуется их использование."},
{en:"behavior-driven development",ru:"разработка через поведение (BDD)",t:"agile",
 de:"A collaborative approach to development in which the team is focusing on delivering expected behavior of a component or system for the customer, which forms the basis for testing.",
 dr:"Совместный подход к разработке, при котором команда фокусируется на обеспечении ожидаемого заказчиком поведения компонента или системы, что и образует основу для тестирования."},
{en:"beta testing",ru:"бета-тестирование",t:"levels",
 de:"A type of acceptance testing performed at an external site to the developer's test environment by roles outside the development organization.",
 dr:"Вид приёмочного тестирования, выполняемый вне тестовой среды разработчика лицами вне организации-разработчика."},
{en:"black-box test technique",ru:"техника тестирования чёрного ящика",t:"tech",
 de:"A test technique based on the specification of a component or system.",
 dr:"Техника тестирования, основанная на спецификации компонента или системы."},
{en:"black-box testing",ru:"тестирование чёрного ящика",t:"types",
 de:"A test approach based on the specification of a component or system.",
 dr:"Подход к тестированию, основанный на спецификации компонента или системы."},
{en:"boundary value",ru:"граничное значение",t:"tech",
 de:"A minimum or maximum value of an ordered equivalence partition.",
 dr:"Минимальное или максимальное значение упорядоченного класса эквивалентности."},
{en:"boundary value analysis",ru:"анализ граничных значений",t:"tech",
 de:"A black-box test technique in which the test conditions are boundary values.",
 dr:"Техника тестирования чёрного ящика, в которой условиями тестирования являются граничные значения."},
{en:"branch",ru:"ветвь",t:"tech",
 de:"A transfer of control between two consecutive nodes in the control flow graph of a test item.",
 dr:"Передача управления между двумя последовательными узлами в графе потока управления тестируемого элемента."},
{en:"branch coverage",ru:"покрытие ветвей",t:"tech",
 de:"The coverage of branches in a control flow graph.",
 dr:"Покрытие ветвей в графе потока управления."},
{en:"branch testing",ru:"тестирование ветвей",t:"tech",
 de:"A white-box test technique in which the test conditions are branches.",
 dr:"Техника тестирования белого ящика, в которой условиями тестирования являются ветви."},
{en:"build verification test",ru:"проверочный тест сборки",t:"auto",
 de:"An automated test that validates the integrity of each new build and verifies its key/core functionality, stability, and testability.",
 dr:"Автоматизированный тест, проверяющий целостность каждой новой сборки, а также её ключевую функциональность, стабильность и тестопригодность."},
{en:"cause-effect diagram",ru:"причинно-следственная диаграмма",t:"defect",
 de:"A graphical representation used to organize and display the interrelationships of various possible root causes of a problem. Possible causes of a real or potential defect or failure are organized in categories and subcategories in a horizontal tree-structure, with the (potential) defect or failure as the root node.",
 dr:"Графическое представление для упорядочивания и отображения взаимосвязей различных возможных коренных причин проблемы. Возможные причины реального или потенциального дефекта/отказа организованы по категориям и подкатегориям в горизонтальной древовидной структуре, где корневым узлом является (потенциальный) дефект или отказ."},
{en:"checklist-based reviewing",ru:"обзор на основе контрольного списка",t:"static",
 de:"A review technique guided by a list of questions or required attributes.",
 dr:"Техника обзора, основанная на списке вопросов или требуемых характеристик."},
{en:"checklist-based testing",ru:"тестирование на основе контрольного списка",t:"tech",
 de:"An experience-based test technique in which test cases are designed to exercise the items of a checklist.",
 dr:"Техника тестирования на основе опыта, в которой тестовые случаи проектируются для проверки пунктов контрольного списка."},
{en:"coding standard",ru:"стандарт кодирования",t:"static",
 de:"A quality standard that defines required characteristics of code.",
 dr:"Стандарт качества, определяющий требуемые характеристики кода."},
{en:"collaboration-based test approach",ru:"подход к тестированию на основе сотрудничества",t:"agile",
 de:"An approach to testing that focuses on defect avoidance by collaborating among stakeholders.",
 dr:"Подход к тестированию, сфокусированный на предотвращении дефектов за счёт сотрудничества между заинтересованными сторонами."},
{en:"compatibility",ru:"совместимость",t:"quality",
 de:"The degree to which a component or system can exchange information with other components or systems, and/or perform its required functions while sharing the same hardware or software environment.",
 dr:"Степень, в которой компонент или система может обмениваться информацией с другими компонентами/системами и/или выполнять свои функции, разделяя ту же аппаратную или программную среду."},
{en:"compliance",ru:"соответствие (нормам)",t:"quality",
 de:"Adherence of a work product to standards, conventions or regulations in laws and similar prescriptions.",
 dr:"Соблюдение рабочим продуктом стандартов, соглашений или предписаний законов и подобных нормативов."},
{en:"component",ru:"компонент",t:"levels",
 de:"A part of a system that can be tested in isolation.",
 dr:"Часть системы, которую можно тестировать изолированно."},
{en:"component integration testing",ru:"интеграционное тестирование компонентов",t:"levels",
 de:"The integration testing of components.",
 dr:"Интеграционное тестирование компонентов между собой."},
{en:"component testing",ru:"компонентное тестирование",t:"levels",
 de:"A test level that focuses on individual hardware or software components.",
 dr:"Уровень тестирования, сфокусированный на отдельных аппаратных или программных компонентах."},
{en:"confirmation testing",ru:"подтверждающее тестирование (ретест)",t:"types",
 de:"A type of change-related testing performed after fixing a defect to confirm that a failure caused by that defect does not reoccur.",
 dr:"Вид тестирования, связанного с изменениями, выполняемый после исправления дефекта, чтобы подтвердить, что вызванный им отказ больше не повторяется."},
{en:"continuous delivery",ru:"непрерывная поставка",t:"agile",
 de:"An automated software development procedure in which code changes are automatically built, tested, and prepared for a release to production.",
 dr:"Автоматизированная процедура разработки ПО, при которой изменения кода автоматически собираются, тестируются и подготавливаются к выпуску в продакшн."},
{en:"continuous deployment",ru:"непрерывное развёртывание",t:"agile",
 de:"An automated software release procedure in which all code changes are deployed to production after all specified tests have passed.",
 dr:"Автоматизированная процедура выпуска ПО, при которой все изменения кода развёртываются в продакшн после прохождения всех заданных тестов."},
{en:"continuous integration",ru:"непрерывная интеграция",t:"agile",
 de:"An automated software development procedure that merges, integrates and tests all changes as soon as they are committed.",
 dr:"Автоматизированная процедура разработки ПО, которая объединяет, интегрирует и тестирует все изменения сразу после их фиксации (commit)."},
{en:"continuous testing",ru:"непрерывное тестирование",t:"agile",
 de:"A test approach that performs testing throughout the software development lifecycle, early and often, and automates tests to obtain feedback as quickly as possible on software release candidates.",
 dr:"Подход к тестированию, при котором тестирование выполняется на протяжении всего жизненного цикла разработки — рано и часто — с автоматизацией тестов для максимально быстрой обратной связи по кандидатам на выпуск."},
{en:"control flow",ru:"поток управления",t:"tech",
 de:"The sequence in which operations are performed by a business process, component or system.",
 dr:"Последовательность, в которой операции выполняются бизнес-процессом, компонентом или системой."},
{en:"cost of quality",ru:"стоимость качества",t:"mgmt",
 de:"The total costs incurred on quality activities and defects, often split into the costs of defect prevention, appraisal, internal failure, and external failure.",
 dr:"Совокупные затраты на деятельность по качеству и на дефекты, часто разделяемые на затраты на предотвращение дефектов, оценку, внутренние отказы и внешние отказы."},
{en:"coverage",ru:"покрытие",t:"tech",
 de:"The degree to which specified coverage items are exercised by a test suite, expressed as a percentage.",
 dr:"Степень, в которой заданные элементы покрытия проверяются набором тестов, выраженная в процентах."},
{en:"coverage criteria",ru:"критерии покрытия",t:"tech",
 de:"The criteria to define the coverage items required to reach a test objective.",
 dr:"Критерии, определяющие элементы покрытия, необходимые для достижения цели тестирования."},
{en:"coverage item",ru:"элемент покрытия",t:"tech",
 de:"An attribute or combination of attributes derived from one or more test conditions by using a test technique.",
 dr:"Атрибут или комбинация атрибутов, выведенные из одного или нескольких условий тестирования с применением техники тестирования."},
{en:"dashboard",ru:"дашборд (панель показателей)",t:"mgmt",
 de:"A representation of dynamic measurements of operational performance for some organization or activity, using metrics represented via metaphors such as visual dials, counters, and other devices resembling those on the dashboard of an automobile, so that the effects of events or activities can be easily understood and related to operational goals.",
 dr:"Представление динамических измерений операционных показателей организации или деятельности с помощью метрик, отображаемых метафорами (визуальные шкалы, счётчики и т. п., как на приборной панели автомобиля), чтобы эффекты событий легко воспринимались и соотносились с операционными целями."},
{en:"debugging",ru:"отладка",t:"fund",
 de:"The process of finding, analyzing and removing the causes of failures in a component or system.",
 dr:"Процесс поиска, анализа и устранения причин отказов в компоненте или системе."},
{en:"decision coverage",ru:"покрытие решений",t:"tech",
 de:"The coverage of decision outcomes.",
 dr:"Покрытие исходов решений (decision outcomes)."},
{en:"decision table testing",ru:"тестирование на основе таблицы решений",t:"tech",
 de:"A black-box test technique in which the test conditions are the combinations of conditions and the resulting actions shown in a decision table.",
 dr:"Техника тестирования чёрного ящика, в которой условиями тестирования являются комбинации условий и соответствующих действий, представленные в таблице решений."},
{en:"defect",ru:"дефект",t:"defect",
 de:"An imperfection or deficiency in a work product where it does not meet its requirements or specifications or impairs its intended use.",
 dr:"Изъян или недостаток в рабочем продукте, из-за которого он не соответствует требованиям/спецификациям или нарушает его предполагаемое использование."},
{en:"defect density",ru:"плотность дефектов",t:"defect",
 de:"The number of defects per unit size of a work product.",
 dr:"Число дефектов на единицу размера рабочего продукта."},
{en:"defect detection percentage",ru:"процент обнаружения дефектов",t:"defect",
 de:"The number of defects found by a test level, divided by the number found by that test level and any other means afterwards.",
 dr:"Число дефектов, найденных на уровне тестирования, делённое на число, найденное этим уровнем и любыми другими средствами впоследствии."},
{en:"defect management",ru:"управление дефектами",t:"defect",
 de:"The process of recognizing, recording, classifying, investigating, fixing and disposing of defects.",
 dr:"Процесс распознавания, регистрации, классификации, исследования, исправления и закрытия дефектов."},
{en:"defect report",ru:"отчёт о дефекте",t:"defect",
 de:"Documentation of the occurrence, nature, and status of a defect.",
 dr:"Документ, описывающий возникновение, характер и статус дефекта."},
{en:"defect taxonomy",ru:"таксономия дефектов",t:"defect",
 de:"A list of categories designed to identify and classify defects.",
 dr:"Список категорий, предназначенный для выявления и классификации дефектов."},
{en:"defect-based test technique",ru:"техника тестирования на основе дефектов",t:"tech",
 de:"A test technique in which test conditions are based on a specific defect type.",
 dr:"Техника тестирования, в которой условия тестирования основаны на конкретном типе дефекта."},
{en:"driver",ru:"драйвер",t:"auto",
 de:"A component or tool that temporarily replaces another component and controls or calls a test item in isolation.",
 dr:"Компонент или инструмент, который временно заменяет другой компонент и управляет/вызывает тестируемый элемент изолированно."},
{en:"dynamic testing",ru:"динамическое тестирование",t:"fund",
 de:"A test approach that involves test execution of a test item.",
 dr:"Подход к тестированию, предполагающий выполнение (запуск) тестируемого элемента."},
{en:"each choice coverage",ru:"покрытие каждого выбора",t:"tech",
 de:"The coverage of equivalence partitions in multiple sets of partitions.",
 dr:"Покрытие классов эквивалентности в нескольких наборах разбиений."},
{en:"effectiveness",ru:"результативность",t:"quality",
 de:"The extent to which correct and complete goals are achieved.",
 dr:"Степень, в которой достигаются корректные и полные цели."},
{en:"efficiency",ru:"эффективность",t:"quality",
 de:"The degree to which resources are expended in relation to results achieved.",
 dr:"Степень расходования ресурсов по отношению к достигнутым результатам."},
{en:"entry criteria",ru:"критерии входа",t:"mgmt",
 de:"The set of conditions for officially starting a defined task.",
 dr:"Набор условий для официального начала определённой задачи."},
{en:"equivalence partition",ru:"класс эквивалентности",t:"tech",
 de:"A subset of a value domain for which a component or system is expected to treat all values the same based on the specification.",
 dr:"Подмножество области значений, для которого ожидается, что компонент или система обрабатывает все значения одинаково согласно спецификации."},
{en:"equivalence partitioning",ru:"разбиение на классы эквивалентности",t:"tech",
 de:"A black-box test technique in which test conditions are equivalence partitions exercised by one representative member of each partition.",
 dr:"Техника тестирования чёрного ящика, в которой условиями тестирования являются классы эквивалентности, проверяемые одним представителем каждого класса."},
{en:"error",ru:"ошибка",t:"defect",
 de:"A human action that results in a defect.",
 dr:"Действие человека, приводящее к дефекту."},
{en:"error guessing",ru:"предугадывание ошибок",t:"tech",
 de:"A test technique in which the tests conditions are based on the tester's knowledge of past failures or failure modes.",
 dr:"Техника тестирования, в которой условия тестирования основаны на знании тестировщиком прошлых отказов или режимов отказа."},
{en:"exhaustive testing",ru:"исчерпывающее тестирование",t:"fund",
 de:"A test approach in which the test suite comprises all combinations of input values and preconditions.",
 dr:"Подход к тестированию, при котором набор тестов охватывает все комбинации входных значений и предусловий."},
{en:"exit criteria",ru:"критерии выхода",t:"mgmt",
 de:"The set of conditions for officially completing a defined task.",
 dr:"Набор условий для официального завершения определённой задачи."},
{en:"expected result",ru:"ожидаемый результат",t:"process",
 de:"The observable predicted behavior of a test item under specified conditions based on its test basis.",
 dr:"Наблюдаемое предсказанное поведение тестируемого элемента при заданных условиях, основанное на базисе тестирования."},
{en:"experience-based test technique",ru:"техника тестирования на основе опыта",t:"tech",
 de:"A test technique based on the tester's experience, knowledge and intuition.",
 dr:"Техника тестирования, основанная на опыте, знаниях и интуиции тестировщика."},
{en:"experience-based testing",ru:"тестирование на основе опыта",t:"tech",
 de:"A test approach based on the tester's experience, knowledge and intuition.",
 dr:"Подход к тестированию, основанный на опыте, знаниях и интуиции тестировщика."},
{en:"exploratory testing",ru:"исследовательское тестирование",t:"tech",
 de:"A test approach in which tests are dynamically designed and executed based on tester's knowledge, exploration of a test item, and previous test results.",
 dr:"Подход к тестированию, при котором тесты динамически проектируются и выполняются на основе знаний тестировщика, исследования объекта и предыдущих результатов тестов."},
{en:"failed",ru:"провален (failed)",t:"process",
 de:"A test result if the actual result does not match the expected result.",
 dr:"Результат теста, когда фактический результат не совпадает с ожидаемым."},
{en:"failure",ru:"отказ (сбой)",t:"defect",
 de:"An event in which a component or system does not meet its requirements within specified limits during its execution.",
 dr:"Событие, при котором компонент или система во время выполнения не отвечает своим требованиям в заданных пределах."},
{en:"fault attack",ru:"атака на дефекты (fault attack)",t:"tech",
 de:"A test technique to evaluate a specific quality characteristic of a test object by attempting to trigger specific failures.",
 dr:"Техника тестирования для оценки конкретной характеристики качества объекта путём попыток спровоцировать определённые отказы."},
{en:"feature-driven development",ru:"разработка на основе функций (FDD)",t:"agile",
 de:"An iterative and incremental software development process driven from a client-valued functionality (feature) perspective. Feature-driven development is mostly used in Agile software development.",
 dr:"Итеративно-инкрементальный процесс разработки ПО, движимый ценной для клиента функциональностью (фичами). Применяется преимущественно в Agile-разработке."},
{en:"finding",ru:"находка (замечание)",t:"defect",
 de:"A result of an evaluation that identifies some important issue, problem, or opportunity.",
 dr:"Результат оценки, выявляющий важный вопрос, проблему или возможность."},
{en:"formal review",ru:"формальный обзор",t:"static",
 de:"A review that follows a defined process with a formally documented output.",
 dr:"Обзор, следующий определённому процессу с формально документированным результатом."},
{en:"functional appropriateness",ru:"функциональная пригодность",t:"quality",
 de:"The degree to which the functions facilitate the accomplishment of specified tasks and objectives.",
 dr:"Степень, в которой функции способствуют выполнению заданных задач и целей."},
{en:"functional completeness",ru:"функциональная полнота",t:"quality",
 de:"The degree to which the set of functions covers all the specified tasks and user objectives.",
 dr:"Степень, в которой набор функций покрывает все заданные задачи и цели пользователя."},
{en:"functional correctness",ru:"функциональная корректность",t:"quality",
 de:"The degree to which a component or system provides the correct results with the needed degree of precision.",
 dr:"Степень, в которой компонент или система выдаёт правильные результаты с необходимой точностью."},
{en:"functional suitability",ru:"функциональная пригодность (соответствие)",t:"quality",
 de:"The degree to which a component or system provides functions that meet stated and implied needs when used under specified conditions.",
 dr:"Степень, в которой компонент или система предоставляет функции, отвечающие заявленным и подразумеваемым потребностям при заданных условиях использования."},
{en:"functional testing",ru:"функциональное тестирование",t:"types",
 de:"A test type to determine the functional suitability of a test object.",
 dr:"Тип тестирования для определения функциональной пригодности объекта тестирования."},
{en:"heuristic",ru:"эвристика",t:"tech",
 de:"A generally recognized rule of thumb that helps to achieve a goal.",
 dr:"Общепризнанное эмпирическое правило, помогающее достичь цели."},
{en:"impact analysis",ru:"анализ влияния",t:"mgmt",
 de:"The identification of all work products affected by a change, including an estimate of the resources needed to accomplish the change.",
 dr:"Выявление всех рабочих продуктов, затронутых изменением, включая оценку ресурсов, необходимых для его выполнения."},
{en:"incremental development model",ru:"инкрементальная модель разработки",t:"agile",
 de:"A type of software development lifecycle model in which the component or system is developed through a series of increments.",
 dr:"Тип модели жизненного цикла разработки ПО, при которой компонент или система разрабатывается через серию инкрементов."},
{en:"independence of testing",ru:"независимость тестирования",t:"fund",
 de:"Separation of responsibilities, which encourages the accomplishment of objective testing.",
 dr:"Разделение обязанностей, способствующее проведению объективного тестирования."},
{en:"informal review",ru:"неформальный обзор",t:"static",
 de:"A type of review that does not follow a defined process and has no formally documented output.",
 dr:"Вид обзора, который не следует определённому процессу и не имеет формально документированного результата."},
{en:"inspection",ru:"инспекция",t:"static",
 de:"A type of formal review that uses defined team roles and measurement to identify defects in a work product, and improve the review process and the software development process.",
 dr:"Вид формального обзора с определёнными ролями в команде и измерениями для выявления дефектов в рабочем продукте и улучшения процессов обзора и разработки ПО."},
{en:"integration testing",ru:"интеграционное тестирование",t:"levels",
 de:"A test level that focuses on interactions between components or systems.",
 dr:"Уровень тестирования, сфокусированный на взаимодействиях между компонентами или системами."},
{en:"integrity",ru:"целостность",t:"quality",
 de:"The degree to which only authorized access and modification is allowed to a component, a system or data.",
 dr:"Степень, в которой к компоненту, системе или данным допускается только авторизованный доступ и изменение."},
{en:"interoperability",ru:"интероперабельность",t:"quality",
 de:"The degree to which two or more components or systems can exchange information and use the information that has been exchanged.",
 dr:"Степень, в которой два или более компонента/системы могут обмениваться информацией и использовать обменянную информацию."},
{en:"iterative development model",ru:"итеративная модель разработки",t:"agile",
 de:"A type of software development lifecycle model in which the component or system is developed through a series of repeated cycles.",
 dr:"Тип модели жизненного цикла разработки ПО, при которой компонент или система разрабатывается через серию повторяющихся циклов."},
{en:"maintainability",ru:"сопровождаемость",t:"quality",
 de:"The degree to which a component or system can be modified by the intended maintainers.",
 dr:"Степень, в которой компонент или система может быть изменена предполагаемым персоналом сопровождения."},
{en:"maintenance",ru:"сопровождение",t:"process",
 de:"The process of modifying a component or system after delivery to correct defects, improve quality characteristics, or adapt to a changed environment.",
 dr:"Процесс изменения компонента или системы после поставки для исправления дефектов, улучшения характеристик качества или адаптации к изменившейся среде."},
{en:"maintenance testing",ru:"тестирование сопровождения",t:"types",
 de:"A test type that evaluates the effect of changes made to an operational system or its environment.",
 dr:"Тип тестирования, оценивающий влияние изменений, внесённых в работающую систему или её среду."},
{en:"maturity",ru:"зрелость",t:"quality",
 de:"(1) The capability of an organization with respect to the effectiveness and efficiency of its processes and work practices. (2) The degree to which a component or system meets needs for reliability under normal operation.",
 dr:"(1) Способность организации в части результативности и эффективности её процессов и практик. (2) Степень, в которой компонент или система отвечает потребностям в надёжности при нормальной работе."},
{en:"mean time to failure",ru:"среднее время до отказа",t:"quality",
 de:"The average time from the start of operation to a failure for a component or system.",
 dr:"Среднее время от начала работы до отказа компонента или системы."},
{en:"measurement",ru:"измерение",t:"mgmt",
 de:"The process of assigning a number or category to an entity to describe an attribute of that entity.",
 dr:"Процесс присвоения числа или категории сущности для описания её атрибута."},
{en:"metric",ru:"метрика",t:"mgmt",
 de:"A measurement scale and the method used for measurement.",
 dr:"Шкала измерения и метод, используемый для измерения."},
{en:"model-based testing",ru:"тестирование на основе моделей",t:"tech",
 de:"Testing based on or involving models.",
 dr:"Тестирование, основанное на моделях или использующее модели."},
{en:"moderator",ru:"модератор",t:"static",
 de:"(1) The person responsible for running review meetings. (2) The person who performs a usability test session.",
 dr:"(1) Лицо, ответственное за проведение встреч обзора. (2) Лицо, проводящее сессию тестирования удобства использования."},
{en:"N-switch coverage",ru:"покрытие N-переключений",t:"tech",
 de:"The coverage of sequences of N+1 transitions.",
 dr:"Покрытие последовательностей из N+1 переходов."},
{en:"negative testing",ru:"негативное тестирование",t:"types",
 de:"A test type in which a component or system is used in a way that it is not intended.",
 dr:"Тип тестирования, при котором компонент или система используются не по назначению."},
{en:"non-functional testing",ru:"нефункциональное тестирование",t:"types",
 de:"A test type to evaluate that a component or system complies with non-functional requirements.",
 dr:"Тип тестирования для оценки соответствия компонента или системы нефункциональным требованиям."},
{en:"operational acceptance testing",ru:"эксплуатационное приёмочное тестирование",t:"levels",
 de:"A type of acceptance testing performed to determine whether the organization responsible for operating the system can accept it.",
 dr:"Вид приёмочного тестирования для определения, может ли организация, ответственная за эксплуатацию системы, принять её."},
{en:"pair testing",ru:"парное тестирование",t:"tech",
 de:"A test approach in which two team members simultaneously collaborate on testing a work product.",
 dr:"Подход к тестированию, при котором два члена команды одновременно совместно тестируют рабочий продукт."},
{en:"passed",ru:"пройден (passed)",t:"process",
 de:"A test result if the actual result matches the expected result.",
 dr:"Результат теста, когда фактический результат совпадает с ожидаемым."},
{en:"performance efficiency",ru:"эффективность производительности",t:"quality",
 de:"The degree to which a component or system uses time, resources, and capacity to perform its functions under specified conditions.",
 dr:"Степень, в которой компонент или система использует время, ресурсы и ёмкость для выполнения своих функций при заданных условиях."},
{en:"planning poker",ru:"покер планирования",t:"agile",
 de:"A consensus-based estimation technique, mostly used to estimate effort or relative size of user stories in Agile software development. It is a variation of the Wideband Delphi method using a deck of cards with values representing the units in which the team estimates.",
 dr:"Техника оценки на основе консенсуса, чаще используемая для оценки трудозатрат или относительного размера пользовательских историй в Agile. Вариация метода Wideband Delphi с колодой карт, значения которых соответствуют единицам оценки команды."},
{en:"portability",ru:"переносимость",t:"quality",
 de:"The degree to which a component or system can be transferred from one hardware, software or other operational or usage environment to another.",
 dr:"Степень, в которой компонент или система может быть перенесена из одной аппаратной, программной или иной среды эксплуатации/использования в другую."},
{en:"postcondition",ru:"постусловие",t:"process",
 de:"The expected state of a test item and its test environment at the end of test execution.",
 dr:"Ожидаемое состояние тестируемого элемента и его тестовой среды по завершении выполнения теста."},
{en:"precondition",ru:"предусловие",t:"process",
 de:"The required state of a test item and its test environment prior to test execution.",
 dr:"Требуемое состояние тестируемого элемента и его тестовой среды перед выполнением теста."},
{en:"priority",ru:"приоритет",t:"defect",
 de:"The level of importance assigned to a task according to specific criteria.",
 dr:"Уровень важности, присвоенный задаче согласно определённым критериям."},
{en:"product risk",ru:"продуктовый риск",t:"risk",
 de:"A risk that impacts the quality of a product.",
 dr:"Риск, влияющий на качество продукта."},
{en:"project risk",ru:"проектный риск",t:"risk",
 de:"A risk that impacts project success.",
 dr:"Риск, влияющий на успех проекта."},
{en:"quality",ru:"качество",t:"fund",
 de:"The degree to which a work product satisfies stated and implied requirements.",
 dr:"Степень, в которой рабочий продукт удовлетворяет заявленным и подразумеваемым требованиям."},
{en:"quality assurance",ru:"обеспечение качества (QA)",t:"fund",
 de:"Activities focused on providing confidence that quality requirements will be fulfilled.",
 dr:"Деятельность, направленная на обеспечение уверенности в том, что требования к качеству будут выполнены."},
{en:"quality characteristic",ru:"характеристика качества",t:"quality",
 de:"A category of quality attributes that bears on work product quality.",
 dr:"Категория атрибутов качества, влияющих на качество рабочего продукта."},
{en:"quality control",ru:"контроль качества (QC)",t:"fund",
 de:"Activities designed to evaluate the quality of a component or system.",
 dr:"Деятельность, предназначенная для оценки качества компонента или системы."},
{en:"quality risk",ru:"риск качества",t:"risk",
 de:"A product risk or a project risk impacting quality management.",
 dr:"Продуктовый или проектный риск, влияющий на управление качеством."},
{en:"reactive testing",ru:"реактивное тестирование",t:"tech",
 de:"A test approach that dynamically responds to the behavior of a test object and to test results being obtained.",
 dr:"Подход к тестированию, динамически реагирующий на поведение объекта и на получаемые результаты тестов."},
{en:"regression testing",ru:"регрессионное тестирование",t:"types",
 de:"A type of change-related testing to detect whether defects have been introduced or uncovered in unchanged areas of the software.",
 dr:"Вид тестирования, связанного с изменениями, для выявления, не были ли внесены или обнаружены дефекты в неизменённых областях ПО."},
{en:"regulatory acceptance testing",ru:"нормативное приёмочное тестирование",t:"levels",
 de:"A type of acceptance testing performed to determine the compliance of a test object.",
 dr:"Вид приёмочного тестирования для определения соответствия объекта тестирования нормативным требованиям."},
{en:"reliability",ru:"надёжность",t:"quality",
 de:"The degree to which a component or system performs specified functions under specified conditions for a specified period of time.",
 dr:"Степень, в которой компонент или система выполняет заданные функции при заданных условиях в течение заданного периода времени."},
{en:"requirement",ru:"требование",t:"process",
 de:"A provision that contains criteria to be fulfilled.",
 dr:"Положение, содержащее критерии, которые должны быть выполнены."},
{en:"requirements-based testing",ru:"тестирование на основе требований",t:"tech",
 de:"A black-box test technique in which test conditions are derived from atomic requirements.",
 dr:"Техника тестирования чёрного ящика, в которой условия тестирования выводятся из атомарных требований."},
{en:"retrospective",ru:"ретроспектива",t:"agile",
 de:"A regular event in which team members discuss results, review their practices, and identify ways to improve.",
 dr:"Регулярное мероприятие, на котором команда обсуждает результаты, анализирует практики и определяет пути улучшения."},
{en:"review",ru:"обзор (ревью)",t:"static",
 de:"A type of static testing in which the quality of a work product or process is evaluated by individuals.",
 dr:"Вид статического тестирования, при котором качество рабочего продукта или процесса оценивается людьми."},
{en:"reviewer",ru:"рецензент",t:"static",
 de:"A participant in a review who identifies defects in the work product.",
 dr:"Участник обзора, который выявляет дефекты в рабочем продукте."},
{en:"risk",ru:"риск",t:"risk",
 de:"A factor that could result in future negative consequences.",
 dr:"Фактор, который может привести к будущим негативным последствиям."},
{en:"risk analysis",ru:"анализ рисков",t:"risk",
 de:"The overall process of risk identification and risk assessment.",
 dr:"Общий процесс идентификации и оценки рисков."},
{en:"risk assessment",ru:"оценка рисков",t:"risk",
 de:"The process to examine identified risks and determine the risk level.",
 dr:"Процесс изучения выявленных рисков и определения их уровня."},
{en:"risk control",ru:"управление рисками (контроль)",t:"risk",
 de:"The overall process of risk mitigation and risk monitoring.",
 dr:"Общий процесс снижения рисков и их мониторинга."},
{en:"risk identification",ru:"идентификация рисков",t:"risk",
 de:"The process of finding, recognizing and describing risks.",
 dr:"Процесс поиска, распознавания и описания рисков."},
{en:"risk impact",ru:"воздействие риска",t:"risk",
 de:"The damage that will be caused if a risk becomes an actual outcome or event.",
 dr:"Ущерб, который будет причинён, если риск станет реальным исходом или событием."},
{en:"risk level",ru:"уровень риска",t:"risk",
 de:"The measure of a risk defined by risk impact and risk likelihood.",
 dr:"Мера риска, определяемая воздействием риска и вероятностью риска."},
{en:"risk likelihood",ru:"вероятность риска",t:"risk",
 de:"The probability that a risk will become an actual outcome or event.",
 dr:"Вероятность того, что риск станет реальным исходом или событием."},
{en:"risk management",ru:"управление рисками",t:"risk",
 de:"The process for handling risks.",
 dr:"Процесс работы с рисками."},
{en:"risk mitigation",ru:"снижение рисков",t:"risk",
 de:"The process through which decisions are reached and protective measures are implemented for reducing or maintaining risks to specified levels.",
 dr:"Процесс принятия решений и внедрения защитных мер для снижения или удержания рисков на заданных уровнях."},
{en:"risk monitoring",ru:"мониторинг рисков",t:"risk",
 de:"The activity that checks and reports the status of known risks to stakeholders.",
 dr:"Деятельность по проверке и информированию заинтересованных сторон о статусе известных рисков."},
{en:"risk-based testing",ru:"тестирование на основе рисков",t:"risk",
 de:"A test approach in which the management, selection, prioritization, and use of test activities and resources are based on corresponding risk types and risk levels.",
 dr:"Подход к тестированию, при котором управление, выбор, приоритизация и использование тестовых активностей и ресурсов основаны на соответствующих типах и уровнях рисков."},
{en:"root cause",ru:"коренная причина",t:"defect",
 de:"A source of a defect such that if it is removed, the occurrence of the defect type is decreased or removed.",
 dr:"Источник дефекта, при устранении которого возникновение данного типа дефектов уменьшается или прекращается."},
{en:"root cause analysis",ru:"анализ коренных причин",t:"defect",
 de:"An analysis technique aimed at identifying the root causes of defects.",
 dr:"Техника анализа, направленная на выявление коренных причин дефектов."},
{en:"safety",ru:"безопасность (для жизни)",t:"quality",
 de:"The degree to which a component or system under defined conditions can avoid endangering human life, health, property, or the environment.",
 dr:"Степень, в которой компонент или система при заданных условиях может избегать угрозы жизни, здоровью, имуществу или окружающей среде."},
{en:"scalability",ru:"масштабируемость",t:"quality",
 de:"The degree to which a component or system can be adjusted for changing capacity.",
 dr:"Степень, в которой компонент или система может быть приспособлена к изменяющейся ёмкости (нагрузке)."},
{en:"scenario-based reviewing",ru:"обзор на основе сценариев",t:"static",
 de:"A review technique in which a work product is evaluated to determine its ability to address specific scenarios.",
 dr:"Техника обзора, при которой рабочий продукт оценивается на способность обрабатывать конкретные сценарии."},
{en:"scribe",ru:"секретарь (scribe)",t:"static",
 de:"A person who records information at a review meeting.",
 dr:"Лицо, фиксирующее информацию на встрече обзора."},
{en:"security",ru:"безопасность (защищённость)",t:"quality",
 de:"The degree to which a component or system defends against security attacks and provides access appropriate to types and levels of authorization.",
 dr:"Степень, в которой компонент или система защищается от атак и предоставляет доступ, соответствующий типам и уровням авторизации."},
{en:"sequential development model",ru:"последовательная модель разработки",t:"agile",
 de:"A type of software development lifecycle model in which a complete system is developed in a linear way of several discrete and successive phases with no overlap between them.",
 dr:"Тип модели жизненного цикла, при которой система разрабатывается линейно через несколько дискретных последовательных фаз без перекрытия между ними."},
{en:"service virtualization",ru:"виртуализация сервисов",t:"auto",
 de:"A technique to enable the delivery of virtual services which are deployed, accessed and managed remotely.",
 dr:"Техника, позволяющая предоставлять виртуальные сервисы, которые развёртываются, используются и управляются удалённо."},
{en:"session-based test management",ru:"управление тестированием на основе сессий",t:"mgmt",
 de:"A method for measuring and managing session-based testing.",
 dr:"Метод измерения и управления тестированием на основе сессий."},
{en:"session-based testing",ru:"тестирование на основе сессий",t:"tech",
 de:"A test approach in which test activities are planned as test sessions.",
 dr:"Подход к тестированию, при котором тестовые активности планируются как тестовые сессии."},
{en:"severity",ru:"серьёзность (severity)",t:"defect",
 de:"The degree of impact that a defect has on the development or operation of a component or system.",
 dr:"Степень влияния дефекта на разработку или эксплуатацию компонента или системы."},
{en:"shift left",ru:"сдвиг влево (shift left)",t:"agile",
 de:"A test approach to perform testing and quality assurance activities as early as possible in the software development lifecycle.",
 dr:"Подход, при котором тестирование и работы по обеспечению качества выполняются как можно раньше в жизненном цикле разработки."},
{en:"simulator",ru:"симулятор",t:"auto",
 de:"A component or system used during testing which behaves or operates like a given component or system.",
 dr:"Компонент или система, используемые при тестировании, которые ведут себя или работают подобно заданному компоненту или системе."},
{en:"smoke test",ru:"дымовое тестирование (smoke)",t:"types",
 de:"A test suite that covers the main functionality of a component or system to determine whether it works properly before planned testing begins.",
 dr:"Набор тестов, покрывающий основную функциональность компонента или системы, чтобы определить, работает ли она должным образом перед началом запланированного тестирования."},
{en:"software development lifecycle",ru:"жизненный цикл разработки ПО (SDLC)",t:"agile",
 de:"The activities performed at each phase in software development, and how they relate to one another logically and chronologically.",
 dr:"Деятельность, выполняемая на каждой фазе разработки ПО, и то, как фазы связаны логически и хронологически."},
{en:"software lifecycle",ru:"жизненный цикл ПО",t:"agile",
 de:"The period of time that begins when a software product is conceived and ends when the software is no longer available for use. The software lifecycle typically includes a concept phase, requirements phase, design phase, implementation phase, test phase, installation and checkout phase, operation and maintenance phase, and sometimes, retirement phase. Note these phases may overlap or be performed iteratively.",
 dr:"Период времени, начинающийся с замысла программного продукта и заканчивающийся, когда ПО больше не используется. Обычно включает фазы: концепции, требований, проектирования, реализации, тестирования, установки и проверки, эксплуатации и сопровождения, иногда — вывода из эксплуатации. Фазы могут перекрываться или выполняться итеративно."},
{en:"state transition testing",ru:"тестирование переходов состояний",t:"tech",
 de:"A black-box test technique in which test conditions are state transitions or sequences of them.",
 dr:"Техника тестирования чёрного ящика, в которой условиями тестирования являются переходы состояний или их последовательности."},
{en:"static analysis",ru:"статический анализ",t:"static",
 de:"The automated process of evaluating a component or system without executing it, based on its form, structure, content, or documentation.",
 dr:"Автоматизированный процесс оценки компонента или системы без её выполнения — на основе формы, структуры, содержимого или документации."},
{en:"static testing",ru:"статическое тестирование",t:"static",
 de:"A test approach that does not involve the execution of a test item.",
 dr:"Подход к тестированию, не предполагающий выполнения (запуска) тестируемого элемента."},
{en:"stub",ru:"заглушка (stub)",t:"auto",
 de:"A type of test double providing predefined responses.",
 dr:"Тип тестового дублёра, предоставляющий заранее заданные ответы."},
{en:"system integration testing",ru:"системное интеграционное тестирование",t:"levels",
 de:"A test level that focuses on the integration of systems.",
 dr:"Уровень тестирования, сфокусированный на интеграции систем между собой."},
{en:"system testing",ru:"системное тестирование",t:"levels",
 de:"A test level that focuses on verifying that a system as a whole meets specified requirements.",
 dr:"Уровень тестирования, сфокусированный на проверке того, что система в целом отвечает заданным требованиям."},
{en:"system under test",ru:"тестируемая система (SUT)",t:"process",
 de:"A type of test object that is a system.",
 dr:"Тип объекта тестирования, представляющий собой систему."},
{en:"technical review",ru:"технический обзор",t:"static",
 de:"A formal review by technical experts that examine the quality of a work product and identify discrepancies from specifications and standards.",
 dr:"Формальный обзор техническими экспертами, которые оценивают качество рабочего продукта и выявляют отклонения от спецификаций и стандартов."},
{en:"test",ru:"тест",t:"process",
 de:"A set of one or more test cases.",
 dr:"Набор из одного или нескольких тестовых случаев."},
{en:"test analysis",ru:"анализ тестирования",t:"process",
 de:"The activity that identifies test conditions by analyzing the test basis.",
 dr:"Деятельность по выявлению условий тестирования путём анализа базиса тестирования."},
{en:"test approach",ru:"подход к тестированию",t:"mgmt",
 de:"The manner of implementing test tasks.",
 dr:"Способ реализации задач тестирования."},
{en:"test automation",ru:"автоматизация тестирования",t:"auto",
 de:"The conversion of test activities to automated operation.",
 dr:"Перевод тестовых активностей в автоматизированный режим выполнения."},
{en:"test automation approach",ru:"подход к автоматизации тестирования",t:"auto",
 de:"A test approach to automate test activities.",
 dr:"Подход к тестированию, направленный на автоматизацию тестовых активностей."},
{en:"test automation framework",ru:"фреймворк автоматизации тестирования",t:"auto",
 de:"A set of test harnesses and test libraries for test automation.",
 dr:"Набор тестовых обвязок и тестовых библиотек для автоматизации тестирования."},
{en:"test basis",ru:"базис тестирования",t:"process",
 de:"The body of knowledge used as the basis for test analysis and test design.",
 dr:"Совокупность знаний, используемая как основа для анализа и проектирования тестов."},
{en:"test case",ru:"тестовый случай (тест-кейс)",t:"process",
 de:"A set of preconditions, inputs, actions (where applicable), expected results and postconditions, developed based on test conditions.",
 dr:"Набор предусловий, входных данных, действий (где применимо), ожидаемых результатов и постусловий, разработанный на основе условий тестирования."},
{en:"test charter",ru:"тестовый чартер",t:"process",
 de:"Documentation of a test objective for a test session.",
 dr:"Документация цели тестирования для тестовой сессии."},
{en:"test completion",ru:"завершение тестирования",t:"process",
 de:"The activity that makes testware available for later use, leaves test environments in a satisfactory condition and communicates the results of testing to relevant stakeholders.",
 dr:"Деятельность, которая делает тестовые активы доступными для дальнейшего использования, оставляет тестовые среды в удовлетворительном состоянии и сообщает результаты тестирования заинтересованным сторонам."},
{en:"test completion report",ru:"отчёт о завершении тестирования",t:"mgmt",
 de:"A type of test report produced at completion milestones that provides an evaluation of the corresponding test items against exit criteria.",
 dr:"Вид отчёта о тестировании, создаваемый на вехах завершения, который даёт оценку соответствующих тестовых элементов по критериям выхода."},
{en:"test condition",ru:"условие тестирования",t:"process",
 de:"A testable aspect of a component or system that is intended to be tested.",
 dr:"Тестируемый аспект компонента или системы, который планируется протестировать."},
{en:"test control",ru:"управление тестированием (контроль)",t:"mgmt",
 de:"The activity that develops and applies corrective actions to get a test project on track when it deviates from what was planned.",
 dr:"Деятельность по разработке и применению корректирующих действий для возврата тестового проекта в плановое русло при отклонениях."},
{en:"test cycle",ru:"цикл тестирования",t:"process",
 de:"An instance of the test process against a single identifiable version of the test object.",
 dr:"Экземпляр процесса тестирования относительно одной идентифицируемой версии объекта тестирования."},
{en:"test data",ru:"тестовые данные",t:"process",
 de:"Data needed for test execution.",
 dr:"Данные, необходимые для выполнения теста."},
{en:"test data preparation",ru:"подготовка тестовых данных",t:"process",
 de:"The activity to select data from existing databases or create, generate, manipulate and edit data for testing.",
 dr:"Деятельность по выбору данных из существующих баз либо созданию, генерации, изменению и редактированию данных для тестирования."},
{en:"test design",ru:"проектирование тестов",t:"process",
 de:"The activity that derives and specifies test cases from test conditions.",
 dr:"Деятельность по выведению и описанию тестовых случаев из условий тестирования."},
{en:"test environment",ru:"тестовая среда",t:"process",
 de:"An environment containing hardware, instrumentation, simulators, software tools, and other support elements needed to perform a test.",
 dr:"Среда, содержащая оборудование, инструментарий, симуляторы, программные инструменты и другие вспомогательные элементы, необходимые для выполнения теста."},
{en:"test estimation",ru:"оценка трудозатрат тестирования",t:"mgmt",
 de:"An approximation related to various aspects of testing.",
 dr:"Приближённая оценка, относящаяся к различным аспектам тестирования."},
{en:"test execution",ru:"выполнение тестов",t:"process",
 de:"The activity that runs a test on a component or system producing actual results.",
 dr:"Деятельность по запуску теста на компоненте или системе с получением фактических результатов."},
{en:"test execution automation",ru:"автоматизация выполнения тестов",t:"auto",
 de:"The use of software, e.g., capture/playback tools, to control the execution of tests, the comparison of actual results to expected results, the setting up of test preconditions, and other test control and reporting functions.",
 dr:"Использование ПО (например, инструментов записи/воспроизведения) для управления выполнением тестов, сравнения фактических результатов с ожидаемыми, установки предусловий и других функций управления и отчётности."},
{en:"test execution schedule",ru:"расписание выполнения тестов",t:"mgmt",
 de:"A schedule for the execution of test suites within a test cycle.",
 dr:"Расписание выполнения наборов тестов в рамках цикла тестирования."},
{en:"test harness",ru:"тестовая обвязка",t:"auto",
 de:"A collection of drivers and test doubles needed to execute a test suite.",
 dr:"Набор драйверов и тестовых дублёров, необходимых для выполнения набора тестов."},
{en:"test implementation",ru:"реализация тестов",t:"process",
 de:"The activity that prepares the testware needed for test execution.",
 dr:"Деятельность по подготовке тестовых активов, необходимых для выполнения тестов."},
{en:"test item",ru:"тестируемый элемент",t:"process",
 de:"A part of a test object used in the test process.",
 dr:"Часть объекта тестирования, используемая в процессе тестирования."},
{en:"test level",ru:"уровень тестирования",t:"levels",
 de:"A specific instantiation of a test process.",
 dr:"Конкретное воплощение процесса тестирования."},
{en:"test log",ru:"журнал тестирования",t:"process",
 de:"A chronological record of relevant details about test execution.",
 dr:"Хронологическая запись значимых деталей о выполнении тестов."},
{en:"test management",ru:"управление тестированием",t:"mgmt",
 de:"The process of planning, scheduling, estimating, monitoring, reporting, controlling, and completing test activities.",
 dr:"Процесс планирования, составления расписания, оценки, мониторинга, отчётности, контроля и завершения тестовых активностей."},
{en:"test manager",ru:"менеджер тестирования",t:"mgmt",
 de:"The person responsible for managing test activities, test resources, and evaluating the test object.",
 dr:"Лицо, ответственное за управление тестовыми активностями, ресурсами и за оценку объекта тестирования."},
{en:"test monitoring",ru:"мониторинг тестирования",t:"mgmt",
 de:"The activity that checks the status of testing activities, identifies any variances from planned or expected, and reports status to stakeholders.",
 dr:"Деятельность по проверке статуса тестовых активностей, выявлению отклонений от плана/ожиданий и информированию заинтересованных сторон."},
{en:"test object",ru:"объект тестирования",t:"process",
 de:"The work product to be tested.",
 dr:"Рабочий продукт, подлежащий тестированию."},
{en:"test objective",ru:"цель тестирования",t:"fund",
 de:"The purpose for testing.",
 dr:"Назначение (цель) тестирования."},
{en:"test plan",ru:"план тестирования",t:"mgmt",
 de:"Documentation that describes test objectives, means and schedule for achieving test coordination.",
 dr:"Документация, описывающая цели тестирования, средства и расписание для координации тестирования."},
{en:"test planning",ru:"планирование тестирования",t:"mgmt",
 de:"The activity of establishing or updating a test plan.",
 dr:"Деятельность по созданию или обновлению плана тестирования."},
{en:"test policy",ru:"политика тестирования",t:"mgmt",
 de:"High-level documentation describing the principles, approach and major objectives of the organization regarding testing.",
 dr:"Высокоуровневая документация, описывающая принципы, подход и основные цели организации в отношении тестирования."},
{en:"test procedure",ru:"тестовая процедура",t:"process",
 de:"A sequence of test cases in execution order and any associated actions that may be required to set up the initial preconditions and any wrap-up activities after execution.",
 dr:"Последовательность тестовых случаев в порядке выполнения и связанные действия, необходимые для установки начальных предусловий и завершающих действий после выполнения."},
{en:"test process",ru:"процесс тестирования",t:"fund",
 de:"A set of test activities performed to achieve a test objective.",
 dr:"Набор тестовых активностей, выполняемых для достижения цели тестирования."},
{en:"test progress",ru:"прогресс тестирования",t:"mgmt",
 de:"The progress of testing against a baseline.",
 dr:"Прогресс тестирования относительно базовой линии (baseline)."},
{en:"test progress report",ru:"отчёт о прогрессе тестирования",t:"mgmt",
 de:"A type of periodic test report that includes the progress of test activities against a baseline, risks, and alternatives requiring a decision.",
 dr:"Вид периодического отчёта, включающий прогресс тестовых активностей относительно базовой линии, риски и требующие решения альтернативы."},
{en:"test pyramid",ru:"пирамида тестирования",t:"auto",
 de:"A graphical model representing the relationship of the amount of testing per level, with more at the bottom than at the top.",
 dr:"Графическая модель, отображающая соотношение объёма тестирования по уровням: внизу его больше, чем наверху."},
{en:"test report",ru:"отчёт о тестировании",t:"mgmt",
 de:"Documentation summarizing testing and test results.",
 dr:"Документация, обобщающая тестирование и его результаты."},
{en:"test reporting",ru:"отчётность по тестированию",t:"mgmt",
 de:"The activity that consolidates test monitoring information and evaluates whether test objectives have been reached to inform stakeholders.",
 dr:"Деятельность по консолидации данных мониторинга и оценке достижения целей тестирования для информирования заинтересованных сторон."},
{en:"test result",ru:"результат теста",t:"process",
 de:"The status of the execution of a test.",
 dr:"Статус выполнения теста."},
{en:"test run",ru:"тестовый прогон",t:"process",
 de:"The execution of a test suite on a specific version of the test object.",
 dr:"Выполнение набора тестов на конкретной версии объекта тестирования."},
{en:"test schedule",ru:"расписание тестирования",t:"mgmt",
 de:"A list of activities, tasks, and milestones of the test process, their intended start and finish dates and interdependencies.",
 dr:"Список активностей, задач и вех процесса тестирования с их планируемыми датами начала/окончания и взаимозависимостями."},
{en:"test scope",ru:"область тестирования",t:"mgmt",
 de:"A description of the test object and its features to be tested.",
 dr:"Описание объекта тестирования и его функций, подлежащих тестированию."},
{en:"test script",ru:"тестовый скрипт",t:"process",
 de:"A sequence of instructions for the execution of a test.",
 dr:"Последовательность инструкций для выполнения теста."},
{en:"test session",ru:"тестовая сессия",t:"process",
 de:"An uninterrupted period of time spent in executing tests.",
 dr:"Непрерывный период времени, затраченный на выполнение тестов."},
{en:"test specification",ru:"спецификация тестов",t:"process",
 de:"The complete documentation of the test design, test cases, and test scripts for a specific test item.",
 dr:"Полная документация проектирования тестов, тестовых случаев и скриптов для конкретного тестируемого элемента."},
{en:"test strategy",ru:"стратегия тестирования",t:"mgmt",
 de:"A description of how to perform testing to reach test objectives under given circumstances.",
 dr:"Описание того, как проводить тестирование для достижения целей при заданных обстоятельствах."},
{en:"test suite",ru:"набор тестов",t:"process",
 de:"A set of test scripts or test procedures to be executed in a specific test run.",
 dr:"Набор тестовых скриптов или процедур для выполнения в конкретном тестовом прогоне."},
{en:"test technique",ru:"техника тестирования",t:"tech",
 de:"A procedure used to define test conditions, design test cases, and specify test data.",
 dr:"Процедура, используемая для определения условий тестирования, проектирования тестовых случаев и задания тестовых данных."},
{en:"test type",ru:"тип тестирования",t:"types",
 de:"A group of test activities based on specific test objectives aimed at specific characteristics of a component or system.",
 dr:"Группа тестовых активностей, основанных на конкретных целях и направленных на конкретные характеристики компонента или системы."},
{en:"test-driven development",ru:"разработка через тестирование (TDD)",t:"agile",
 de:"A software development technique in which the test cases are developed, automated and then the software is developed incrementally to pass those test cases.",
 dr:"Техника разработки ПО, при которой тестовые случаи разрабатываются и автоматизируются, а затем ПО создаётся инкрементально, чтобы проходить эти тесты."},
{en:"test-first approach",ru:"подход «тест вперёд»",t:"agile",
 de:"An approach to software development in which the test cases are designed and implemented before the associated component or system is developed.",
 dr:"Подход к разработке ПО, при котором тестовые случаи проектируются и реализуются до создания соответствующего компонента или системы."},
{en:"testability",ru:"тестопригодность",t:"quality",
 de:"The degree to which test conditions can be established for a component or system, and tests can be performed to determine whether those test conditions have been met.",
 dr:"Степень, в которой для компонента или системы можно установить условия тестирования и выполнить тесты, чтобы определить их выполнение."},
{en:"tester",ru:"тестировщик",t:"fund",
 de:"A person who performs testing.",
 dr:"Лицо, выполняющее тестирование."},
{en:"testing",ru:"тестирование",t:"fund",
 de:"The process within the software development lifecycle that evaluates the quality of a component or system and related work products.",
 dr:"Процесс в рамках жизненного цикла разработки ПО, оценивающий качество компонента или системы и связанных рабочих продуктов."},
{en:"testing quadrants",ru:"квадранты тестирования",t:"agile",
 de:"A classification model of test types/test levels in four quadrants, relating them to two dimensions of test objectives: supporting the product team versus critiquing the product, and technology-facing versus business-facing.",
 dr:"Классификационная модель типов/уровней тестирования в четырёх квадрантах, связывающая их с двумя измерениями целей: поддержка команды против критики продукта и ориентация на технологию против ориентации на бизнес."},
{en:"testware",ru:"тестовые активы (testware)",t:"process",
 de:"Work products produced during the test process for use in planning, designing, executing, evaluating and reporting on testing.",
 dr:"Рабочие продукты, создаваемые в процессе тестирования для планирования, проектирования, выполнения, оценки и отчётности по тестированию."},
{en:"traceability",ru:"трассируемость",t:"mgmt",
 de:"The ability to establish explicit relationships between related work products or items within work products.",
 dr:"Способность устанавливать явные связи между связанными рабочими продуктами или элементами внутри них."},
{en:"unit test framework",ru:"фреймворк модульного тестирования",t:"auto",
 de:"A tool that provides an environment for testing a unit in isolation.",
 dr:"Инструмент, предоставляющий среду для тестирования модуля изолированно."},
{en:"usability",ru:"удобство использования (usability)",t:"quality",
 de:"The degree to which a component or system can be used by specified users to achieve specified goals in a specified context of use.",
 dr:"Степень, в которой компонент или система может использоваться заданными пользователями для достижения заданных целей в заданном контексте использования."},
{en:"usability lab",ru:"лаборатория юзабилити",t:"quality",
 de:"A test facility in which unintrusive observation of participant reactions and responses to software takes place.",
 dr:"Тестовая площадка, где проводится ненавязчивое наблюдение за реакциями и откликами участников на ПО."},
{en:"usability testing",ru:"тестирование удобства использования",t:"types",
 de:"Testing to evaluate the degree to which the system can be used by specified users with effectiveness, efficiency and satisfaction in a specified context of use.",
 dr:"Тестирование для оценки того, насколько система может использоваться заданными пользователями с результативностью, эффективностью и удовлетворённостью в заданном контексте."},
{en:"user acceptance testing",ru:"пользовательское приёмочное тестирование (UAT)",t:"levels",
 de:"A type of acceptance testing performed to determine if intended users accept the system.",
 dr:"Вид приёмочного тестирования для определения, принимают ли систему её предполагаемые пользователи."},
{en:"user experience",ru:"пользовательский опыт (UX)",t:"quality",
 de:"A person's perceptions and responses resulting from the use or anticipated use of a software product.",
 dr:"Восприятие и реакции человека, возникающие в результате использования или ожидаемого использования программного продукта."},
{en:"user interface",ru:"пользовательский интерфейс (UI)",t:"process",
 de:"All components of a system that provide information and controls for the user to accomplish specific tasks with the system.",
 dr:"Все компоненты системы, предоставляющие пользователю информацию и элементы управления для выполнения конкретных задач."},
{en:"user story",ru:"пользовательская история",t:"agile",
 de:"A short narrative describing a need from a user's perspective together with the expected benefit when this need is satisfied.",
 dr:"Краткое описание потребности с точки зрения пользователя вместе с ожидаемой выгодой при её удовлетворении."},
{en:"V-model",ru:"V-модель",t:"agile",
 de:"A sequential software development lifecycle model describing a one-for-one relationship between major phases of software development from business requirements specification to delivery, and corresponding test levels from acceptance testing to component testing.",
 dr:"Последовательная модель жизненного цикла, описывающая взаимно-однозначную связь между основными фазами разработки (от спецификации бизнес-требований до поставки) и соответствующими уровнями тестирования (от приёмочного до компонентного)."},
{en:"validation",ru:"валидация",t:"fund",
 de:"Confirmation by examination that a work product matches a stakeholder's needs.",
 dr:"Подтверждение путём проверки того, что рабочий продукт соответствует потребностям заинтересованной стороны."},
{en:"verification",ru:"верификация",t:"fund",
 de:"The process of confirming that a work product fulfills its specification.",
 dr:"Процесс подтверждения того, что рабочий продукт соответствует своей спецификации."},
{en:"walkthrough",ru:"сквозной просмотр (walkthrough)",t:"static",
 de:"A type of formal review in which an author leads members of the review through a work product and the members ask questions and make comments.",
 dr:"Вид формального обзора, при котором автор проводит участников по рабочему продукту, а они задают вопросы и делают замечания."},
{en:"white-box test technique",ru:"техника тестирования белого ящика",t:"tech",
 de:"A test technique based on the internal structure of a component or system.",
 dr:"Техника тестирования, основанная на внутренней структуре компонента или системы."},
{en:"white-box testing",ru:"тестирование белого ящика",t:"types",
 de:"A test approach based on the internal structure of a component or system.",
 dr:"Подход к тестированию, основанный на внутренней структуре компонента или системы."}
];
